# Generate a alpine-based image dedicated to build software from source (alpine-src)
FROM alpine
MAINTAINER babonet13 <admin@hubject.net>
RUN apk update
# Meta-package wich install the most common developement
RUN apk add alpine-sdk
