FROM ubuntu
MAINTAINER babonet13 <admin@hubject.net>
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y automake
RUN apt-get install -y libtool
RUN apt-get install -y python3
