FROM ubuntu
MAINTAINER babonet13 <admin@hubject.net>
RUN apt-get update
# Package dedicated to check authenticity
RUN apt-get install -y ca-certificate
# Package dedicated to manage packages
RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common
